/**
 * The module grid's pixel art, extracted from the game rather than traced by
 * hand (`scripts/extract-grid-icons.py`, regenerated by `bun run extract`).
 *
 * Each sprite is SVG path data at its native pixel size, split into one path
 * per distinct colour. `shade` is that colour's brightness against the
 * sprite's brightest one, so painting every layer in a single CSS colour at
 * `fill-opacity: shade` reproduces the sprite's own shading in whatever colour
 * the module happens to be. Shade 0 is the sprite's black — its outline and
 * interior fill — which is the void, not a dark tint of the module colour.
 *
 * `PixelSprite.svelte` is the one renderer; nothing else should read `layers`.
 */

import gridIcons from './grid-icons.json';

export interface SpriteLayer {
	/** Brightness against the sprite's brightest colour. 0 is its black. */
	shade: number;
	/** The colour in the game's own art, before the editor recolours it. */
	color: string;
	d: string;
}

export interface GridSprite {
	w: number;
	h: number;
	/** The asset it came out of, for tracing a change back after a game update. */
	source: string;
	layers: SpriteLayer[];
}

const sprites = gridIcons.sprites as unknown as Record<string, GridSprite>;

/**
 * One grid cell in game pixels — the widest module frame the game ships, so a
 * frame either fills its cell or centres in it, and what is left over is the
 * gap between two neighbours. Every position in the grid editor counts in these.
 */
export const GRID_CELL: number = gridIcons.cell;

export const SLOT_EMPTY = sprites.slotEmpty;
export const SLOT_BOOST = sprites.slotBoost;
export const SLOT_BLOCKED = sprites.slotBlocked;
/** The octagon every special slot (weapon, gadget, embedded) wears while empty. */
export const SLOT_SPECIAL = sprites.slotSpecial;
/** A module's connection point: the open ring when nothing answers it. */
export const NOTCH = sprites.notch;
/** The capsule two connected modules share across the seam. */
export const NOTCH_LINKED = sprites.notchLinked;
/** One +1 chevron, drawn once per level above the base. */
export const BOOST_PIP = sprites.boostPip;

/** The frame a module wears, by its shop category (`moduleCategory`). */
export function moduleFrame(category: string): GridSprite {
	return sprites[`frame:${category}`] ?? sprites['frame:UPGRADES'];
}

/** Where a sprite starts when it is centred in the cell. */
export function centredIn(sprite: GridSprite): number {
	return (GRID_CELL - sprite.w) / 2;
}
