"""Rip the PUNK wordmark and derive the outline mask the title animation needs.

Unlike the other extractors these outputs are *page art*, not game data, so they
land in static/ as PNGs rather than in src/lib/game as base64 JSON — the title
screen references them from CSS (`mask-image`), which can't read a JSON blob.

Two files come out of one sprite:

- `punk-wordmark.png` — the sprite as shipped: 153x39, black fill with a white
  outline on transparent. Drawn onto the page's black background it simply *is*
  the logo, so the crisp centre copy is a plain <img>.
- `punk-wordmark-outline.png` — the white pixels only, as an alpha mask. This is
  what the echo layers use, and it is the whole reason the effect reads
  correctly: masking with the sprite's own alpha gives solid letter shapes, and
  a stack of those merges into one blob. The game's echoes are copies of the
  *outline*, so scaling them up yields thin nested strokes with black between
  them — the tunnel you actually see in main_title_logo_animation.mp4.

Run via scripts/extract-all.py, or directly:
    .venv/Scripts/python.exe scripts/extract-logo.py
"""

from __future__ import annotations

from pathlib import Path

from PIL import Image

import punklib

# The main menu's own title sprite. It lives in the UI atlas under Unity's
# autogenerated placeholder name rather than anything like "logo".
SPRITE_NAME = "MainMenu_placeholders_0"
STATIC_DIR = punklib.REPO / "static"


def outline_mask(mark: Image.Image) -> Image.Image:
    """White pixels -> opaque; fill and background -> transparent."""
    px = mark.load()
    mask = Image.new("L", mark.size, 0)
    mp = mask.load()
    for y in range(mark.height):
        for x in range(mark.width):
            r, g, b, a = px[x, y]
            if a > 128 and r > 200 and g > 200 and b > 200:
                mp[x, y] = 255
    return mask


def main() -> None:
    assets = punklib.PunkAssets(punklib.game_data_from_argv())

    mark = None
    for obj in assets.env.objects:
        if obj.type.name != "Sprite":
            continue
        try:
            data = obj.read()
        except Exception:
            continue
        if (data.m_Name or "") == SPRITE_NAME:
            mark = data.image.convert("RGBA")
            break

    if mark is None:
        punklib.warn(f"sprite {SPRITE_NAME!r} not found — did the main menu art get renamed?")
        raise SystemExit(1)

    STATIC_DIR.mkdir(parents=True, exist_ok=True)
    mark.save(STATIC_DIR / "punk-wordmark.png")
    print(f"  punk-wordmark.png: {mark.width}x{mark.height}")

    mask = outline_mask(mark)
    lit = sum(1 for y in range(mask.height) for x in range(mask.width) if mask.load()[x, y])
    if not lit:
        punklib.warn("outline mask is empty — the sprite's outline is no longer white")
        raise SystemExit(1)

    # Saved as a white RGBA image whose alpha carries the shape, so it works
    # directly as a CSS mask-image in every engine.
    out = Image.new("RGBA", mark.size, (255, 255, 255, 0))
    out.putalpha(mask)
    out.save(STATIC_DIR / "punk-wordmark-outline.png")
    print(f"  punk-wordmark-outline.png: {lit} outline pixels")


if __name__ == "__main__":
    main()
